import { sql } from "drizzle-orm";
import {
  customType,
  integer,
  jsonb,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { uuidv7 } from "@codevault/core/crypto";

/**
 * Column helpers shared by every table.
 *
 * Keeping these in one place is what makes "all timestamps are timestamptz" and
 * "all primary keys are UUIDv7" true by construction instead of by convention.
 */

/** Primary key: UUIDv7 generated by the application so inserts stay ordered. */
export const primaryId = () =>
  uuid("id")
    .primaryKey()
    .$defaultFn(() => uuidv7());

export const createdAt = () =>
  timestamp("created_at", { withTimezone: true, mode: "string" })
    .notNull()
    .defaultNow();

export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true, mode: "string" })
    .notNull()
    .defaultNow();

export const timestampColumn = (name: string) =>
  timestamp(name, { withTimezone: true, mode: "string" });

/**
 * Optimistic-concurrency counter.
 *
 * Every mutable entity carries one. Updates assert the caller's expected
 * revision, which is how an AI proposal computed against an older version is
 * rejected instead of silently overwriting a researcher's edit.
 */
export const revision = () => integer("revision").notNull().default(1);

/** Free-form metadata object, always present so callers never null-check it. */
export const metadata = (name = "metadata") =>
  jsonb(name)
    .$type<Record<string, unknown>>()
    .notNull()
    .default(sql`'{}'::jsonb`);

/**
 * PostgreSQL `tsvector`.
 *
 * Drizzle has no native mapping, so we declare a custom type. The columns are
 * generated in SQL from the searchable text; this declaration exists so queries
 * can reference them in a typed way.
 */
export const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

export const searchVector = (name = "search_vector") => tsvector(name);
