import { describe, expect, it } from "vitest";

import referenceVectors from "./cvss40-reference-vectors.json" with { type: "json" };
import {
  buildCvss40Vector,
  calculateCvss40,
  CvssVectorError,
  isValidCvss40Vector,
  macroVector,
  parseCvss40Vector,
} from "./cvss40.js";

/**
 * `cvss40-reference-vectors.json` was generated by running the FIRST.org
 * reference calculator (github.com/FIRSTdotorg/cvss-v4-calculator) over a fixed
 * sample of vectors. A mismatch here means CodeVault would publish a score
 * FIRST does not agree with, so it fails CI.
 */
describe("FIRST reference conformance", () => {
  it("covers base, threat and environmental vectors", () => {
    expect(referenceVectors.length).toBeGreaterThanOrEqual(70);
    expect(referenceVectors.some((entry) => entry.vector.includes("/E:"))).toBe(
      true,
    );
    expect(
      referenceVectors.some((entry) => entry.vector.includes("/CR:")),
    ).toBe(true);
  });

  it.each(referenceVectors)("scores $vector as $score", ({ vector, score }) => {
    expect(calculateCvss40(vector).score).toBe(score);
  });
});

describe("well-known vectors", () => {
  it("scores an unauthenticated total-compromise vector at 9.3", () => {
    const result = calculateCvss40(
      "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
    );

    expect(result.score).toBe(9.3);
    expect(result.severity).toBe("CRITICAL");
    // EQ1-3 are at their most severe, EQ4 is 2 because there is no subsequent
    // system impact, EQ5 is 0 because undefined exploit maturity means
    // Attacked, and EQ6 is 0 because CR:H meets VC:H.
    expect(result.macroVector).toBe("000200");
  });

  it("scores full subsequent-system impact at 10.0", () => {
    const result = calculateCvss40(
      "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H",
    );

    expect(result.score).toBe(10);
  });

  it("short-circuits a no-impact vector to zero", () => {
    const result = calculateCvss40(
      "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N",
    );

    expect(result.score).toBe(0);
    expect(result.severity).toBe("NONE");
  });

  it("scores a local privilege escalation at 8.5", () => {
    const result = calculateCvss40(
      "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
    );

    expect(result.score).toBe(8.5);
    expect(result.severity).toBe("HIGH");
  });
});

describe("parseCvss40Vector", () => {
  const base =
    "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N";

  it("returns every supplied metric", () => {
    expect(parseCvss40Vector(base).AV).toBe("N");
  });

  it("rejects a missing prefix", () => {
    expect(() => parseCvss40Vector("AV:N/AC:L")).toThrow(CvssVectorError);
  });

  it("rejects an unknown metric", () => {
    expect(() => parseCvss40Vector(`${base}/ZZ:N`)).toThrow(/Unknown/);
  });

  it("rejects an unknown value", () => {
    expect(() =>
      parseCvss40Vector(
        "CVSS:4.0/AV:Q/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
      ),
    ).toThrow(/not a valid value/);
  });

  it("rejects a duplicated metric", () => {
    expect(() => parseCvss40Vector(`${base}/AV:L`)).toThrow(/more than once/);
  });

  it("rejects a vector missing a mandatory metric", () => {
    expect(() =>
      parseCvss40Vector("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N"),
    ).toThrow(/mandatory/);
  });

  it("reports validity without throwing", () => {
    expect(isValidCvss40Vector(base)).toBe(true);
    expect(isValidCvss40Vector("nonsense")).toBe(false);
  });
});

describe("buildCvss40Vector", () => {
  it("emits metrics in canonical order and drops undefined values", () => {
    const vector = buildCvss40Vector({
      VC: "H",
      AV: "N",
      AC: "L",
      AT: "N",
      PR: "N",
      UI: "N",
      VI: "H",
      VA: "H",
      SC: "N",
      SI: "N",
      SA: "N",
      E: "X",
    });

    expect(vector).toBe(
      "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
    );
  });

  it("round-trips through the parser", () => {
    const original =
      "CVSS:4.0/AV:A/AC:H/AT:P/PR:L/UI:P/VC:L/VI:L/VA:N/SC:H/SI:N/SA:L/E:P";

    expect(buildCvss40Vector(parseCvss40Vector(original))).toBe(original);
  });
});

describe("macroVector", () => {
  it("treats an undefined exploit maturity as attacked", () => {
    const withoutExploitMaturity = macroVector(
      parseCvss40Vector(
        "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
      ),
    );
    const withAttacked = macroVector(
      parseCvss40Vector(
        "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:A",
      ),
    );

    expect(withoutExploitMaturity).toBe(withAttacked);
  });

  it("lets a modified metric override its base counterpart", () => {
    const withoutOverride = macroVector(
      parseCvss40Vector(
        "CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
      ),
    );
    const withOverride = macroVector(
      parseCvss40Vector(
        "CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/MAV:N",
      ),
    );

    expect(withoutOverride).not.toBe(withOverride);
    expect(withOverride.startsWith("0")).toBe(true);
  });
});
